baseurl = "https://cognate.pages.taltech.ee/wiki"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title         = "Cognate"
canonifyurls  = true

DefaultContentLanguage = "en"
theme = "ourtheme"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  subtitle = "Analyzing big data with innovative 5G technologies"
  logo = "img/logo.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "#&&|"

[[menu.main]]
    identifier = "retros"
    name = "The Cognate Project Retros"
    weight = 1

[[menu.main]]
    identifier = "future"
    name = "Future plan"
    weight = 2

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    parent = "retros"
    name = "-1 - Nintendo"
    url = "retros/2021-12-14-nintendo"
    weight = 1

[[menu.main]]
    parent = "retros"
    name = "0 - Tap to start"
    url = "retros/2021-12-20-tap-to-start"
    weight = 2

[[menu.main]]
    parent = "retros"
    name = "1 - The Known World"
    url = "retros/2022-01-04-the-known-world"
    weight = 3

[[menu.main]]
    parent = "retros"
    name = "2 - Challenge to Reality"
    url = "retros/2022-01-16-challenge-to-reality"
    weight = 4

[[menu.main]]
    parent = "retros"
    name = "3 - Refusal of the Call"
    url = "retros/2022-01-23-refusal-of-the-call"
    weight = 5

[[menu.main]]
    parent = "retros"
    name = "4 - Meeting the Mentor"
    url = "retros/2022-01-30-meeting-the-mentor"
    weight = 6

[[menu.main]]
    parent = "retros"
    name = "5 - Cross the Threshold"
    url = "retros/2022-02-06-cross-the-threshold"
    weight = 7

[[menu.main]]
    parent = "retros"
    name = "6 - Prepare for Change"
    url = "retros/2022-02-13-prepare-for-change"
    weight = 8

[[menu.main]]
    parent = "retros"
    name = "7 - Trials and Tribulations"
    url = "retros/2022-02-20-trials-and-tribulations"
    weight = 9

[[menu.main]]
    parent = "retros"
    name = "8 - Deep Work"
    url = "retros/2022-02-27-deep-work"
    weight = 10

[[menu.main]]
    parent = "retros"
    name = "9 - Embodying the Change"
    url = "retros/2022-03-06-embodying-the-change"
    weight = 11

[[menu.main]]
    parent = "retros"
    name = "10 - Return to the World"
    url = "retros/2022-03-13-return-to-world"
    weight = 12

[[menu.main]]
    parent = "retros"
    name = "11 - Deliver new Level"
    url = "retros/2022-03-20-deliver-new-level"
    weight = 13

[[menu.main]]
    parent = "retros"
    name = "12 - Inspire Others"
    url = "retros/2022-03-27-inspire-others"
    weight = 14

[[menu.main]]
    parent = "retros"
    name = "13 - The Known World"
    url = "retros/2022-04-03-the-known-world"
    weight = 15

[[menu.main]]
    parent = "retros"
    name = "14 - Challenge to reality"
    url = "retros/2022-04-10-challenge-to-reality"
    weight = 16

[[menu.main]]
    parent = "retros"
    name = "15 - Post-structual Monumentality"
    url = "retros/2022-04-17-post-structual-monumentality"
    weight = 16

[[menu.main]]
    parent = "retros"
    name = "16 - Commune"
    url = "retros/2022-04-24-commune"
    weight = 17

[[menu.main]]
    parent = "retros"
    name = "17 - Natural Habitat"
    url = "retros/2022-05-02-natural-habitat"
    weight = 18

[[menu.main]]
    parent = "retros"
    name = "18 - Global Village"
    url = "retros/2022-05-09-global-village"
    weight = 19

[[menu.main]]
    parent = "retros"
    name = "19 - If you plan if for one year, plant rice"
    url = "retros/2022-05-16-plant-rice"
    weight = 20

[[menu.main]]
    parent = "retros"
    name = "20 - If you plan if for ten years, plant trees"
    url = "retros/2022-05-23-plant-trees"
    weight = 21

[[menu.main]]
    parent = "retros"
    name = "21 - If you plan if for 100 years, educate children"
    url = "retros/2022-05-31-educate-children"
    weight = 22